# Site settings
metatitle: FreeBetCash - Your guide to match betting
title: Your complete guide to all free bets
description: "with the best Australian bookies"
baseurl: "/" # the subpath of your site, e.g. /blog/
root: /jeklayback
url: "http://andrew1980uk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#excerpt
excerpt_separator: <!--more-->

collections:
  bookies:
    permalink: /:path/