# Site settings
metatitle: Bonus Money - Your guide to match betting
title: Your guide to match betting!
description: "Learn how to make money quickly and easily with us"
baseurl: "/" # the subpath of your site, e.g. /blog/
root: /jeklayback
url: "http://andrew1980uk.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#excerpt
excerpt_separator: <!--more-->

collections:
  bookies:
    permalink: /:path/