# Site settings
title: Bookie reviews!
description: "Your guide to match betting!"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.bonusbet.com.au" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

#excerpt
excerpt_separator: <!--more-->

collections:
  bookies:
    foo: bar
    permalink: /reviews/:path/